## Fine-Tunning of station status parameters

In this notebook, we analyze changes in status behaviours varying station parameters of a group of selected stations.

### Module imports

In this section, we load checklist modules to be able to use in main script file. It's required to run only one time bellow cell due to every new execution change current execution path. In other case it's required to restart jupyter variables.

In [ ]:
## Trick to change current location
%cd ..
import numpy as np
import pandas as pd
import time
from datetime import datetime, UTC
from tqdm import tqdm
from src.config import settings
from src.data_access.slinktool_executor import SlinktoolExecutor
from src.data_access.load_data import StationRepository
from src.services.delay_calculator import DelayCalculator
from src.services.station_analysis import StationAnalysis
from src.utilities.data_formatter import SiigeoFormatter, OtherStationsFormatter
from src.utilities.slinktool_formatter import SlinktoolFormatter

/home/wpenaranda/error_404/check_list

### Load station information from SGC

In [2]:
# Load stations data
siigeo_data = StationRepository.get_siigeo_stations()
shared_data = StationRepository.get_shared_stations()
inter_data = StationRepository.get_inter_stations()

data = {'siigeo': siigeo_data, 'shared': shared_data, 'inter': inter_data}
format_data = {}
for key, df in data.items():
    strategy = SiigeoFormatter() if key == 'siigeo' else OtherStationsFormatter()
    df = strategy.rename_cols(df)
    df = strategy.assign_data_types(df)
    df = strategy.infer_channel(df)
    df = strategy.filter_data(df)
    df = strategy.default_connection(df)
    format_data[key] = df     

siigeo_data = format_data['siigeo']
shared_data = format_data['shared']
inter_data = format_data['inter']
all_data = pd.concat([siigeo_data, shared_data, inter_data], ignore_index=True)

20:35:06 [INFO] Stations from Siigeo file succesfully load.
20:35:06 [INFO] Shared stations succesfully load.
20:35:06 [INFO] International stations succesfully load.
20:35:06 [INFO] Dataframe formatted succesfully. n=208
20:35:06 [INFO] Dataframe formatted succesfully. n=20
20:35:06 [INFO] Dataframe formatted succesfully. n=65

### Test time differences between validations.

Here, we test time differences between validations, for this case we propose following cases: (5 s, 10 s, 15 s, 30 s, 45 s, 60 s, 90 s) with a selection of a sample of stations to analyze any variations in delays and possible station status.

About stations, we select three different groups of stations: 

- stations that always are online in actual checklist.
- stations that usually have status from recovering to offline, but they usually recover information throughout the day. 
- stations that usually are offline.

According to actual date (03 August, 2026), we select these stations: first group: ARAMC, CHI, DBB and GUY2C; second group: BRJC, AGCC, POP2 and PPLP and thirth group: MEDEC, MOCC, GMALF and UPD2.

#### Time difference = 5 s

In [ ]:
# Request slinktool data 
port = SlinktoolExecutor.get_port('91')
comm = SlinktoolExecutor.build_command('91', port)
output = SlinktoolExecutor.request_info(comm)
solution = SlinktoolFormatter.extract_info(output)
slink_data = SlinktoolFormatter.build_dataframe(solution)
slink_data = SlinktoolFormatter.select_interest_channels(slink_data)
slink_data = SlinktoolFormatter.assign_transmission(slink_data, all_data)
slink_data = SlinktoolFormatter.order_cols(slink_data)

import warnings
with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=FutureWarning)
    final_data = DelayCalculator.add_stations_untracked(all_data, slink_data)

# Compute Delay Time
actual_time = datetime.now(UTC).replace(tzinfo=None)
final_data = DelayCalculator.compute_delays(final_data, actual_time, 'last_connection')
final_data = DelayCalculator.format_delays(final_data, delay_column='delay')
print(f'to = {actual_time}')

# Second request
period_time = 5
with tqdm(total=period_time, desc=f"Waiting {period_time} seconds to execute a new validation") as pbar:
        for _ in range(period_time):
                time.sleep(1)
                pbar.update(1)

output = SlinktoolExecutor.request_info(comm)
solution = SlinktoolFormatter.extract_info(output)
slink_data = SlinktoolFormatter.build_dataframe(solution)
slink_data = SlinktoolFormatter.select_interest_channels(slink_data)
slink_data = SlinktoolFormatter.assign_transmission(slink_data, all_data)
slink_data = SlinktoolFormatter.order_cols(slink_data)

with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=FutureWarning)
    final_data2 = DelayCalculator.add_stations_untracked(all_data, slink_data)
actual_time = datetime.now(UTC).replace(tzinfo=None)
final_data2 = DelayCalculator.compute_delays(final_data2, actual_time, 'last_connection')
final_data2 = DelayCalculator.format_delays(final_data2, delay_column='delay')

# Extract delay columns
delay1 = final_data['delay'].dt.total_seconds().fillna(np.nan).to_numpy()
delay2 = final_data2['delay'].dt.total_seconds().fillna(np.nan).to_numpy()
status = StationAnalysis.get_station_status(delay1, delay2, period_time)
final_data2['delay1_seconds'] = delay1
final_data2['delay2_seconds'] = delay2
final_data2['status'] = status
print(f'to = {actual_time}')

# Subset stations of interest 
interm_sts = ['BRJC', 'POP2', 'AGCC', 'PPLP']
perma_sts = ['ARAMC', 'CHI', 'DBB', 'GUY2C']
off_sts = ['MEDEC', 'MOCC', 'GMALF', 'UPD2']
cols = ['stid', 'loc', 'channel', 'last_connection', 'delay1_seconds', 'delay2_seconds', 'status']
res = final_data2.loc[final_data2['stid'].isin([*perma_sts, *interm_sts, *off_sts])]
res = res[cols]
res.head(50)

20:36:26 [INFO] Port stablished succesfully.
20:36:26 [INFO] Sucessful information request from slinktool.
20:36:26 [INFO] Number of sensors to be processed: 1518
20:36:26 [INFO] Success!!
20:36:26 [INFO] Dataframe created succesfully!!
20:36:26 [INFO] Selection of the 792 field sensors completed succesfully!!
20:36:26 [INFO] Transmission type assigned succesfully!!
20:36:26 [INFO] Dataframe formatted succesfully according to SGC data!!
20:36:26 [INFO] Adding stations not tracked by slinktool succesfully!!
20:36:26 [INFO] Delays succesfully computed!!
20:36:26 [INFO] Delays succesfully formatted!!

to = 2026-08-04 01:36:26.180885

Waiting 5 seconds to execute a new validation: 100%|██████████| 5/5 [00:05<00:00,  1.00s/it]
20:36:31 [INFO] Sucessful information request from slinktool.
20:36:31 [INFO] Number of sensors to be processed: 1518
20:36:31 [INFO] Success!!
20:36:31 [INFO] Dataframe created succesfully!!
20:36:31 [INFO] Selection of the 792 field sensors completed succesfully!!
20:36:31 [INFO] Transmission type assigned succesfully!!
20:36:31 [INFO] Dataframe formatted succesfully according to SGC data!!
20:36:31 [INFO] Adding stations not tracked by slinktool succesfully!!
20:36:31 [INFO] Delays succesfully computed!!
20:36:31 [INFO] Delays succesfully formatted!!

to = 2026-08-04 01:36:31.311678

,stid,loc,channel,last_connection,delay1_seconds,delay2_seconds,status
15,AGCC,00,HHE,2026-08-03 05:05:29.970000,7.385621e+04,7.386134e+04,Offline
16,AGCC,00,HHN,2026-08-03 05:05:30.470000,7.385571e+04,7.386084e+04,Offline
17,AGCC,00,HHZ,2026-08-03 05:05:29.750000,7.385643e+04,7.386156e+04,Offline
27,ARAMC,00,HHE,2026-08-04 01:36:30,4.420885e+00,1.311678e+00,Online
28,ARAMC,00,HHN,2026-08-04 01:36:30.010000,4.410885e+00,1.301678e+00,Online
29,ARAMC,00,HHZ,2026-08-04 01:36:28.240000,2.060885e+00,3.071678e+00,Online
75,BRJC,00,HHE,2026-08-03 21:08:17.640000,1.608854e+04,1.609367e+04,Offline
76,BRJC,00,HHN,2026-08-03 21:08:17.950000,1.608823e+04,1.609336e+04,Offline
77,BRJC,00,HHZ,2026-08-03 21:08:16.360000,1.608982e+04,1.609495e+04,Offline
78,BRJC,10,HNE,2026-08-03 21:08:17.730000,1.608845e+04,1.609358e+04,Offline
79,BRJC,10,HNN,2026-08-03 21:08:16.740000,1.608944e+04,1.609457e+04,Offline
80,BRJC,10,HNZ,2026-08-03 21:08:18.650000,1.608753e+04,1.609266e+04,Offline
138,CHI,00,HHE,2026-08-04 01:36:10.968300,1.521259e+01,2.034338e+01,intermittent
139,CHI,00,HHN,2026-08-04 01:36:09.808300,1.637259e+01,2.150338e+01,intermittent
140,CHI,00,HHZ,2026-08-04 01:36:12.188300,1.399259e+01,1.912338e+01,intermittent
141,CHI,10,HNE,2026-08-04 01:36:29.670000,3.295885e+00,1.641678e+00,Online
142,CHI,10,HNN,2026-08-04 01:36:28.120000,2.295885e+00,3.191678e+00,Online
143,CHI,10,HNZ,2026-08-04 01:36:28.810000,1.910885e+00,2.501678e+00,Online
243,DBB,00,HHE,2026-08-04 01:36:19.298300,6.882585e+00,1.201338e+01,intermittent
244,DBB,00,HHN,2026-08-04 01:36:22.048300,4.132585e+00,9.263378e+00,intermittent
245,DBB,00,HHZ,2026-08-04 01:36:20.318300,5.862585e+00,1.099338e+01,intermittent
246,DBB,10,HNE,2026-08-04 01:36:27.795000,5.590885e+00,3.516678e+00,Online
247,DBB,10,HNN,2026-08-04 01:36:24,5.740885e+00,7.311678e+00,Online
248,DBB,10,HNZ,2026-08-04 01:36:24.375000,5.320885e+00,6.936678e+00,Online
249,DBB,20,EHE,2026-08-04 01:36:21.128300,5.052585e+00,1.018338e+01,intermittent
250,DBB,20,EHN,2026-08-04 01:36:21.788300,4.392585e+00,9.523378e+00,intermittent
251,DBB,20,EHZ,2026-08-04 01:36:18.858300,7.322585e+00,1.245338e+01,intermittent
318,GUY2C,00,HHE,2026-08-04 01:36:22.490000,3.690885e+00,8.821678e+00,intermittent
319,GUY2C,00,HHN,2026-08-04 01:36:23.860000,2.320885e+00,7.451678e+00,intermittent
320,GUY2C,00,HHZ,2026-08-04 01:36:25.040000,8.050885e+00,6.271678e+00,Online
321,GUY2C,10,HNE,2026-08-04 01:36:29.885000,3.085885e+00,1.426678e+00,Online
322,GUY2C,10,HNN,2026-08-04 01:36:28.675000,4.650885e+00,2.636678e+00,Online
323,GUY2C,10,HNZ,2026-08-04 01:36:30.035000,3.315885e+00,1.276678e+00,Online
360,MEDEC,10,HNE,2026-05-29 04:49:43.195000,5.777203e+06,5.777208e+06,Offline
361,MEDEC,10,HNN,2026-05-29 04:49:42.430000,5.777204e+06,5.777209e+06,Offline
362,MEDEC,10,HNZ,2026-05-29 04:49:42.840000,5.777203e+06,5.777208e+06,Offline
363,MOCC,10,HNE,2026-04-19 15:22:27.465000,9.195239e+06,9.195244e+06,Offline
364,MOCC,10,HNN,2026-04-19 15:22:27.935000,9.195238e+06,9.195243e+06,Offline
365,MOCC,10,HNZ,2026-04-19 15:22:27.560000,9.195239e+06,9.195244e+06,Offline
447,POP2,00,HHE,2026-08-04 00:14:02.968300,4.943213e+03,4.948343e+03,Offline
448,POP2,00,HHN,2026-08-04 00:14:02.968300,4.943213e+03,4.948343e+03,Offline
449,POP2,00,HHZ,2026-08-04 00:14:02.968300,4.943213e+03,4.948343e+03,Offline
450,POP2,40,HLE,2026-08-04 00:14:03.984500,4.942196e+03,4.947327e+03,Offline
451,POP2,40,HLN,2026-08-04 00:14:03.984500,4.942196e+03,4.947327e+03,Offline
452,POP2,40,HLZ,2026-08-04 00:14:03.984500,4.942196e+03,4.947327e+03,Offline
686,PPLP,<NA>,HHE,2026-08-04 01:36:19.368300,6.812585e+00,1.194338e+01,intermittent
687,PPLP,<NA>,HHN,2026-08-04 01:36:21.128300,5.052585e+00,1.018338e+01,intermittent
688,PPLP,<NA>,HHZ,2026-08-04 01:36:18.568300,7.612585e+00,1.274338e+01,intermittent
799,POP2,10,HNZ,None,NaN,NaN,N/A
816,GMALF,,HNZ,None,NaN,NaN,N/A

Analyzing results, we note an inconsistency in status for CHI, DBB, GUY2C stations. Status is assigned to intermitent for some sensors (particularly broadband and short-period), but the acelerographs are online. Additionaly, when we look closely his diference in delay times are a little bit higher than 5.1 seconds.

#### Time difference = 10 s

In [ ]:
# Request slinktool data 
port = SlinktoolExecutor.get_port('91')
comm = SlinktoolExecutor.build_command('91', port)
output = SlinktoolExecutor.request_info(comm)
solution = SlinktoolFormatter.extract_info(output)
slink_data = SlinktoolFormatter.build_dataframe(solution)
slink_data = SlinktoolFormatter.select_interest_channels(slink_data)
slink_data = SlinktoolFormatter.assign_transmission(slink_data, all_data)
slink_data = SlinktoolFormatter.order_cols(slink_data)

import warnings
with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=FutureWarning)
    final_data = DelayCalculator.add_stations_untracked(all_data, slink_data)

# Compute Delay Time
actual_time = datetime.now(UTC).replace(tzinfo=None)
final_data = DelayCalculator.compute_delays(final_data, actual_time, 'last_connection')
final_data = DelayCalculator.format_delays(final_data, delay_column='delay')
print(f'to = {actual_time}')

# Second request
period_time = 10
with tqdm(total=period_time, desc=f"Waiting {period_time} seconds to execute a new validation") as pbar:
        for _ in range(period_time):
                time.sleep(1)
                pbar.update(1)

output = SlinktoolExecutor.request_info(comm)
solution = SlinktoolFormatter.extract_info(output)
slink_data = SlinktoolFormatter.build_dataframe(solution)
slink_data = SlinktoolFormatter.select_interest_channels(slink_data)
slink_data = SlinktoolFormatter.assign_transmission(slink_data, all_data)
slink_data = SlinktoolFormatter.order_cols(slink_data)

with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=FutureWarning)
    final_data2 = DelayCalculator.add_stations_untracked(all_data, slink_data)
actual_time = datetime.now(UTC).replace(tzinfo=None)
final_data2 = DelayCalculator.compute_delays(final_data2, actual_time, 'last_connection')
final_data2 = DelayCalculator.format_delays(final_data2, delay_column='delay')

# Extract delay columns
delay1 = final_data['delay'].dt.total_seconds().fillna(np.nan).to_numpy()
delay2 = final_data2['delay'].dt.total_seconds().fillna(np.nan).to_numpy()
status = StationAnalysis.get_station_status(delay1, delay2, period_time)
final_data2['delay1_seconds'] = delay1
final_data2['delay2_seconds'] = delay2
final_data2['status'] = status
print(f'to = {actual_time}')

# Subset stations of interest 
interm_sts = ['BRJC', 'POP2', 'AGCC', 'PPLP']
perma_sts = ['ARAMC', 'CHI', 'DBB', 'GUY2C']
off_sts = ['MEDEC', 'MOCC', 'GMALF', 'UPD2']
cols = ['stid', 'loc', 'channel', 'last_connection', 'delay1_seconds', 'delay2_seconds', 'status']
res = final_data2.loc[final_data2['stid'].isin([*perma_sts, *interm_sts, *off_sts])]
res = res[cols]
res.head(50)

20:51:33 [INFO] Port stablished succesfully.
20:51:33 [INFO] Sucessful information request from slinktool.
20:51:33 [INFO] Number of sensors to be processed: 1518
20:51:33 [INFO] Success!!
20:51:33 [INFO] Dataframe created succesfully!!
20:51:33 [INFO] Selection of the 792 field sensors completed succesfully!!
20:51:33 [INFO] Transmission type assigned succesfully!!
20:51:33 [INFO] Dataframe formatted succesfully according to SGC data!!
20:51:33 [INFO] Adding stations not tracked by slinktool succesfully!!
20:51:33 [INFO] Delays succesfully computed!!
20:51:33 [INFO] Delays succesfully formatted!!

to = 2026-08-04 01:51:33.568886

Waiting 10 seconds to execute a new validation: 100%|██████████| 10/10 [00:10<00:00,  1.00s/it]
20:51:43 [INFO] Sucessful information request from slinktool.
20:51:43 [INFO] Number of sensors to be processed: 1518
20:51:43 [INFO] Success!!
20:51:43 [INFO] Dataframe created succesfully!!
20:51:43 [INFO] Selection of the 792 field sensors completed succesfully!!
20:51:43 [INFO] Transmission type assigned succesfully!!
20:51:43 [INFO] Dataframe formatted succesfully according to SGC data!!
20:51:43 [INFO] Adding stations not tracked by slinktool succesfully!!
20:51:43 [INFO] Delays succesfully computed!!
20:51:43 [INFO] Delays succesfully formatted!!

to = 2026-08-04 01:51:43.715903

,stid,loc,channel,last_connection,delay1_seconds,delay2_seconds,status
15,AGCC,00,HHE,2026-08-03 05:05:29.970000,7.476360e+04,7.477375e+04,Offline
16,AGCC,00,HHN,2026-08-03 05:05:30.470000,7.476310e+04,7.477325e+04,Offline
17,AGCC,00,HHZ,2026-08-03 05:05:29.750000,7.476382e+04,7.477397e+04,Offline
27,ARAMC,00,HHE,2026-08-04 01:51:40.360000,1.448886e+00,3.355903e+00,Online
28,ARAMC,00,HHN,2026-08-04 01:51:40.510000,1.298886e+00,3.205903e+00,Online
29,ARAMC,00,HHZ,2026-08-04 01:51:42.740000,3.188886e+00,9.759030e-01,Online
75,BRJC,00,HHE,2026-08-03 21:08:17.640000,1.699593e+04,1.700608e+04,Offline
76,BRJC,00,HHN,2026-08-03 21:08:17.950000,1.699562e+04,1.700577e+04,Offline
77,BRJC,00,HHZ,2026-08-03 21:08:16.360000,1.699721e+04,1.700736e+04,Offline
78,BRJC,10,HNE,2026-08-03 21:08:17.730000,1.699584e+04,1.700599e+04,Offline
79,BRJC,10,HNN,2026-08-03 21:08:16.740000,1.699683e+04,1.700698e+04,Offline
80,BRJC,10,HNZ,2026-08-03 21:08:18.650000,1.699492e+04,1.700507e+04,Offline
138,CHI,00,HHE,2026-08-04 01:51:22.678300,1.089059e+01,2.103760e+01,intermittent
139,CHI,00,HHN,2026-08-04 01:51:21.458300,1.211059e+01,2.225760e+01,intermittent
140,CHI,00,HHZ,2026-08-04 01:51:23.968300,9.600586e+00,1.974760e+01,intermittent
141,CHI,10,HNE,2026-08-04 01:51:42.045000,5.838860e-01,1.670903e+00,Online
142,CHI,10,HNN,2026-08-04 01:51:41.615000,5.688860e-01,2.100903e+00,Online
143,CHI,10,HNZ,2026-08-04 01:51:42.190000,5.688860e-01,1.525903e+00,Online
243,DBB,00,HHE,2026-08-04 01:51:31.278300,1.543059e+01,1.243760e+01,Online
244,DBB,00,HHN,2026-08-04 01:51:34.748300,1.674059e+01,8.967603e+00,Online
245,DBB,00,HHZ,2026-08-04 01:51:34.958300,1.751059e+01,8.757603e+00,Online
246,DBB,10,HNE,2026-08-04 01:51:35.710000,5.063886e+00,8.005903e+00,Online
247,DBB,10,HNN,2026-08-04 01:51:40.705000,3.553886e+00,3.010903e+00,Online
248,DBB,10,HNZ,2026-08-04 01:51:35.150000,8.888886e+00,8.565903e+00,Online
249,DBB,20,EHE,2026-08-04 01:51:31.828300,1.468059e+01,1.188760e+01,Online
250,DBB,20,EHN,2026-08-04 01:51:32.678300,1.847059e+01,1.103760e+01,Online
251,DBB,20,EHZ,2026-08-04 01:51:31.848300,1.505059e+01,1.186760e+01,Online
318,GUY2C,00,HHE,2026-08-04 01:51:36.050000,4.568886e+00,7.665903e+00,Online
319,GUY2C,00,HHN,2026-08-04 01:51:37.220000,3.418886e+00,6.495903e+00,Online
320,GUY2C,00,HHZ,2026-08-04 01:51:40.350000,7.288886e+00,3.365903e+00,Online
321,GUY2C,10,HNE,2026-08-04 01:51:39.835000,3.868886e+00,3.880903e+00,Online
322,GUY2C,10,HNN,2026-08-04 01:51:39.640000,1.018886e+00,4.075903e+00,Online
323,GUY2C,10,HNZ,2026-08-04 01:51:41.820000,2.423886e+00,1.895903e+00,Online
360,MEDEC,10,HNE,2026-05-29 04:49:43.195000,5.778110e+06,5.778121e+06,Offline
361,MEDEC,10,HNN,2026-05-29 04:49:42.430000,5.778111e+06,5.778121e+06,Offline
362,MEDEC,10,HNZ,2026-05-29 04:49:42.840000,5.778111e+06,5.778121e+06,Offline
363,MOCC,10,HNE,2026-04-19 15:22:27.465000,9.196146e+06,9.196156e+06,Offline
364,MOCC,10,HNN,2026-04-19 15:22:27.935000,9.196146e+06,9.196156e+06,Offline
365,MOCC,10,HNZ,2026-04-19 15:22:27.560000,9.196146e+06,9.196156e+06,Offline
447,POP2,00,HHE,2026-08-04 00:14:02.968300,5.850601e+03,5.860748e+03,Offline
448,POP2,00,HHN,2026-08-04 00:14:02.968300,5.850601e+03,5.860748e+03,Offline
449,POP2,00,HHZ,2026-08-04 00:14:02.968300,5.850601e+03,5.860748e+03,Offline
450,POP2,40,HLE,2026-08-04 00:14:03.984500,5.849584e+03,5.859731e+03,Offline
451,POP2,40,HLN,2026-08-04 00:14:03.984500,5.849584e+03,5.859731e+03,Offline
452,POP2,40,HLZ,2026-08-04 00:14:03.984500,5.849584e+03,5.859731e+03,Offline
686,PPLP,<NA>,HHE,2026-08-04 01:51:36.478300,1.344059e+01,7.237603e+00,Online
687,PPLP,<NA>,HHN,2026-08-04 01:51:38.248300,1.325059e+01,5.467603e+00,Online
688,PPLP,<NA>,HHZ,2026-08-04 01:51:39.268300,1.482059e+01,4.447603e+00,Online
799,POP2,10,HNZ,None,NaN,NaN,N/A
816,GMALF,,HNZ,None,NaN,NaN,N/A

Analyzing results, we note an inconsistency in status for CHI station. Status is assigned to intermitent in broadband sensor, but the acelerographs are online. Additionaly, when we look closely his diference in delay times are a little bit higher than 10 seconds.

### Time difference =  15 s

In [ ]:
# Request slinktool data 
port = SlinktoolExecutor.get_port('91')
comm = SlinktoolExecutor.build_command('91', port)
output = SlinktoolExecutor.request_info(comm)
solution = SlinktoolFormatter.extract_info(output)
slink_data = SlinktoolFormatter.build_dataframe(solution)
slink_data = SlinktoolFormatter.select_interest_channels(slink_data)
slink_data = SlinktoolFormatter.assign_transmission(slink_data, all_data)
slink_data = SlinktoolFormatter.order_cols(slink_data)

import warnings
with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=FutureWarning)
    final_data = DelayCalculator.add_stations_untracked(all_data, slink_data)

# Compute Delay Time
actual_time = datetime.now(UTC).replace(tzinfo=None)
final_data = DelayCalculator.compute_delays(final_data, actual_time, 'last_connection')
final_data = DelayCalculator.format_delays(final_data, delay_column='delay')
print(f'to = {actual_time}')

# Second request
period_time = 15
with tqdm(total=period_time, desc=f"Waiting {period_time} seconds to execute a new validation") as pbar:
        for _ in range(period_time):
                time.sleep(1)
                pbar.update(1)

output = SlinktoolExecutor.request_info(comm)
solution = SlinktoolFormatter.extract_info(output)
slink_data = SlinktoolFormatter.build_dataframe(solution)
slink_data = SlinktoolFormatter.select_interest_channels(slink_data)
slink_data = SlinktoolFormatter.assign_transmission(slink_data, all_data)
slink_data = SlinktoolFormatter.order_cols(slink_data)

with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=FutureWarning)
    final_data2 = DelayCalculator.add_stations_untracked(all_data, slink_data)
actual_time = datetime.now(UTC).replace(tzinfo=None)
final_data2 = DelayCalculator.compute_delays(final_data2, actual_time, 'last_connection')
final_data2 = DelayCalculator.format_delays(final_data2, delay_column='delay')

# Extract delay columns
delay1 = final_data['delay'].dt.total_seconds().fillna(np.nan).to_numpy()
delay2 = final_data2['delay'].dt.total_seconds().fillna(np.nan).to_numpy()
status = StationAnalysis.get_station_status(delay1, delay2, period_time)
final_data2['delay1_seconds'] = delay1
final_data2['delay2_seconds'] = delay2
final_data2['status'] = status
print(f'to = {actual_time}')

# Subset stations of interest 
interm_sts = ['BRJC', 'POP2', 'AGCC', 'PPLP']
perma_sts = ['ARAMC', 'CHI', 'DBB', 'GUY2C']
off_sts = ['MEDEC', 'MOCC', 'GMALF', 'UPD2']
cols = ['stid', 'loc', 'channel', 'last_connection', 'delay1_seconds', 'delay2_seconds', 'status']
res = final_data2.loc[final_data2['stid'].isin([*perma_sts, *interm_sts, *off_sts])]
res = res[cols]
res.head(50)

20:53:01 [INFO] Port stablished succesfully.
20:53:01 [INFO] Sucessful information request from slinktool.
20:53:01 [INFO] Number of sensors to be processed: 1518
20:53:01 [INFO] Success!!
20:53:01 [INFO] Dataframe created succesfully!!
20:53:01 [INFO] Selection of the 792 field sensors completed succesfully!!
20:53:01 [INFO] Transmission type assigned succesfully!!
20:53:01 [INFO] Dataframe formatted succesfully according to SGC data!!
20:53:01 [INFO] Adding stations not tracked by slinktool succesfully!!
20:53:01 [INFO] Delays succesfully computed!!
20:53:01 [INFO] Delays succesfully formatted!!

to = 2026-08-04 01:53:01.395213

Waiting 15 seconds to execute a new validation: 100%|██████████| 15/15 [00:15<00:00,  1.00s/it]
20:53:16 [INFO] Sucessful information request from slinktool.
20:53:16 [INFO] Number of sensors to be processed: 1518
20:53:16 [INFO] Success!!
20:53:16 [INFO] Dataframe created succesfully!!
20:53:16 [INFO] Selection of the 792 field sensors completed succesfully!!
20:53:16 [INFO] Transmission type assigned succesfully!!
20:53:16 [INFO] Dataframe formatted succesfully according to SGC data!!
20:53:16 [INFO] Adding stations not tracked by slinktool succesfully!!
20:53:16 [INFO] Delays succesfully computed!!
20:53:16 [INFO] Delays succesfully formatted!!

to = 2026-08-04 01:53:16.545981

,stid,loc,channel,last_connection,delay1_seconds,delay2_seconds,status
15,AGCC,00,HHE,2026-08-03 05:05:29.970000,7.485143e+04,7.486658e+04,Offline
16,AGCC,00,HHN,2026-08-03 05:05:30.470000,7.485093e+04,7.486608e+04,Offline
17,AGCC,00,HHZ,2026-08-03 05:05:29.750000,7.485165e+04,7.486680e+04,Offline
27,ARAMC,00,HHE,2026-08-04 01:53:15.120000,2.755213e+00,1.425981e+00,Online
28,ARAMC,00,HHN,2026-08-04 01:53:15.270000,2.605213e+00,1.275981e+00,Online
29,ARAMC,00,HHZ,2026-08-04 01:53:13.380000,4.495213e+00,3.165981e+00,Online
75,BRJC,00,HHE,2026-08-03 21:08:17.640000,1.708376e+04,1.709891e+04,Offline
76,BRJC,00,HHN,2026-08-03 21:08:17.950000,1.708345e+04,1.709860e+04,Offline
77,BRJC,00,HHZ,2026-08-03 21:08:16.360000,1.708504e+04,1.710019e+04,Offline
78,BRJC,10,HNE,2026-08-03 21:08:17.730000,1.708367e+04,1.709882e+04,Offline
79,BRJC,10,HNN,2026-08-03 21:08:16.740000,1.708466e+04,1.709981e+04,Offline
80,BRJC,10,HNZ,2026-08-03 21:08:18.650000,1.708275e+04,1.709790e+04,Offline
138,CHI,00,HHE,2026-08-04 01:52:58.478300,1.738691e+01,1.806768e+01,Online
139,CHI,00,HHN,2026-08-04 01:52:58.278300,1.683691e+01,1.826768e+01,Online
140,CHI,00,HHZ,2026-08-04 01:52:56.018300,1.548691e+01,2.052768e+01,Online
141,CHI,10,HNE,2026-08-04 01:53:14.245000,2.920213e+00,2.300981e+00,Online
142,CHI,10,HNN,2026-08-04 01:53:13.985000,2.600213e+00,2.560981e+00,Online
143,CHI,10,HNZ,2026-08-04 01:53:14.100000,1.105213e+00,2.445981e+00,Online
243,DBB,00,HHE,2026-08-04 01:53:10.738300,7.956913e+00,5.807681e+00,Online
244,DBB,00,HHN,2026-08-04 01:53:08.608300,1.073691e+01,7.937681e+00,Online
245,DBB,00,HHZ,2026-08-04 01:53:09.158300,1.104691e+01,7.387681e+00,Online
246,DBB,10,HNE,2026-08-04 01:53:12.885000,2.920213e+00,3.660981e+00,Online
247,DBB,10,HNN,2026-08-04 01:53:08.885000,6.600213e+00,7.660981e+00,Online
248,DBB,10,HNZ,2026-08-04 01:53:09.330000,6.070213e+00,7.215981e+00,Online
249,DBB,20,EHE,2026-08-04 01:53:10.058300,8.486913e+00,6.487681e+00,Online
250,DBB,20,EHN,2026-08-04 01:53:09.538300,9.426913e+00,7.007681e+00,Online
251,DBB,20,EHZ,2026-08-04 01:53:09.788300,9.436913e+00,6.757681e+00,Online
318,GUY2C,00,HHE,2026-08-04 01:53:12.800000,8.725213e+00,3.745981e+00,Online
319,GUY2C,00,HHN,2026-08-04 01:53:14.030000,7.705213e+00,2.515981e+00,Online
320,GUY2C,00,HHZ,2026-08-04 01:53:10.390000,4.635213e+00,6.155981e+00,Online
321,GUY2C,10,HNE,2026-08-04 01:53:14.770000,3.555213e+00,1.775981e+00,Online
322,GUY2C,10,HNN,2026-08-04 01:53:15.525000,3.640213e+00,1.020981e+00,Online
323,GUY2C,10,HNZ,2026-08-04 01:53:14.460000,1.220213e+00,2.085981e+00,Online
360,MEDEC,10,HNE,2026-05-29 04:49:43.195000,5.778198e+06,5.778213e+06,Offline
361,MEDEC,10,HNN,2026-05-29 04:49:42.430000,5.778199e+06,5.778214e+06,Offline
362,MEDEC,10,HNZ,2026-05-29 04:49:42.840000,5.778199e+06,5.778214e+06,Offline
363,MOCC,10,HNE,2026-04-19 15:22:27.465000,9.196234e+06,9.196249e+06,Offline
364,MOCC,10,HNN,2026-04-19 15:22:27.935000,9.196233e+06,9.196249e+06,Offline
365,MOCC,10,HNZ,2026-04-19 15:22:27.560000,9.196234e+06,9.196249e+06,Offline
447,POP2,00,HHE,2026-08-04 00:14:02.968300,5.938427e+03,5.953578e+03,Offline
448,POP2,00,HHN,2026-08-04 00:14:02.968300,5.938427e+03,5.953578e+03,Offline
449,POP2,00,HHZ,2026-08-04 00:14:02.968300,5.938427e+03,5.953578e+03,Offline
450,POP2,40,HLE,2026-08-04 00:14:03.984500,5.937411e+03,5.952561e+03,Offline
451,POP2,40,HLN,2026-08-04 00:14:03.984500,5.937411e+03,5.952561e+03,Offline
452,POP2,40,HLZ,2026-08-04 00:14:03.984500,5.937411e+03,5.952561e+03,Offline
686,PPLP,<NA>,HHE,2026-08-04 01:53:03.268300,1.376691e+01,1.327768e+01,Online
687,PPLP,<NA>,HHN,2026-08-04 01:53:01.108300,1.767691e+01,1.543768e+01,Online
688,PPLP,<NA>,HHZ,2026-08-04 01:53:04.788300,1.675691e+01,1.175768e+01,Online
799,POP2,10,HNZ,None,NaN,NaN,N/A
816,GMALF,,HNZ,None,NaN,NaN,N/A

Analyzing results, we don't find an inconsistency in station status and everything look quite consistent between sensors of the same station.

#### Time difference = 30 s

In [ ]:
# Request slinktool data 
port = SlinktoolExecutor.get_port('91')
comm = SlinktoolExecutor.build_command('91', port)
output = SlinktoolExecutor.request_info(comm)
solution = SlinktoolFormatter.extract_info(output)
slink_data = SlinktoolFormatter.build_dataframe(solution)
slink_data = SlinktoolFormatter.select_interest_channels(slink_data)
slink_data = SlinktoolFormatter.assign_transmission(slink_data, all_data)
slink_data = SlinktoolFormatter.order_cols(slink_data)

import warnings
with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=FutureWarning)
    final_data = DelayCalculator.add_stations_untracked(all_data, slink_data)

# Compute Delay Time
actual_time = datetime.now(UTC).replace(tzinfo=None)
final_data = DelayCalculator.compute_delays(final_data, actual_time, 'last_connection')
final_data = DelayCalculator.format_delays(final_data, delay_column='delay')
print(f'to = {actual_time}')

# Second request
period_time = 30
with tqdm(total=period_time, desc=f"Waiting {period_time} seconds to execute a new validation") as pbar:
        for _ in range(period_time):
                time.sleep(1)
                pbar.update(1)

output = SlinktoolExecutor.request_info(comm)
solution = SlinktoolFormatter.extract_info(output)
slink_data = SlinktoolFormatter.build_dataframe(solution)
slink_data = SlinktoolFormatter.select_interest_channels(slink_data)
slink_data = SlinktoolFormatter.assign_transmission(slink_data, all_data)
slink_data = SlinktoolFormatter.order_cols(slink_data)

with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=FutureWarning)
    final_data2 = DelayCalculator.add_stations_untracked(all_data, slink_data)
actual_time = datetime.now(UTC).replace(tzinfo=None)
final_data2 = DelayCalculator.compute_delays(final_data2, actual_time, 'last_connection')
final_data2 = DelayCalculator.format_delays(final_data2, delay_column='delay')

# Extract delay columns
delay1 = final_data['delay'].dt.total_seconds().fillna(np.nan).to_numpy()
delay2 = final_data2['delay'].dt.total_seconds().fillna(np.nan).to_numpy()
status = StationAnalysis.get_station_status(delay1, delay2, period_time)
final_data2['delay1_seconds'] = delay1
final_data2['delay2_seconds'] = delay2
final_data2['status'] = status
print(f'to = {actual_time}')

# Subset stations of interest 
interm_sts = ['BRJC', 'POP2', 'AGCC', 'PPLP']
perma_sts = ['ARAMC', 'CHI', 'DBB', 'GUY2C']
off_sts = ['MEDEC', 'MOCC', 'GMALF', 'UPD2']
cols = ['stid', 'loc', 'channel', 'last_connection', 'delay1_seconds', 'delay2_seconds', 'status']
res = final_data2.loc[final_data2['stid'].isin([*perma_sts, *interm_sts, *off_sts])]
res = res[cols]
res.head(50)

20:56:17 [INFO] Port stablished succesfully.
20:56:17 [INFO] Sucessful information request from slinktool.
20:56:17 [INFO] Number of sensors to be processed: 1518
20:56:17 [INFO] Success!!
20:56:17 [INFO] Dataframe created succesfully!!
20:56:17 [INFO] Selection of the 792 field sensors completed succesfully!!
20:56:17 [INFO] Transmission type assigned succesfully!!
20:56:17 [INFO] Dataframe formatted succesfully according to SGC data!!
20:56:17 [INFO] Adding stations not tracked by slinktool succesfully!!
20:56:17 [INFO] Delays succesfully computed!!
20:56:17 [INFO] Delays succesfully formatted!!

to = 2026-08-04 01:56:17.525440

Waiting 30 seconds to execute a new validation: 100%|██████████| 30/30 [00:30<00:00,  1.00s/it]
20:56:47 [INFO] Sucessful information request from slinktool.
20:56:47 [INFO] Number of sensors to be processed: 1517
20:56:47 [INFO] Success!!
20:56:47 [INFO] Dataframe created succesfully!!
20:56:47 [INFO] Selection of the 792 field sensors completed succesfully!!
20:56:47 [INFO] Transmission type assigned succesfully!!
20:56:47 [INFO] Dataframe formatted succesfully according to SGC data!!
20:56:47 [INFO] Adding stations not tracked by slinktool succesfully!!
20:56:47 [INFO] Delays succesfully computed!!
20:56:47 [INFO] Delays succesfully formatted!!

to = 2026-08-04 01:56:47.700679

,stid,loc,channel,last_connection,delay1_seconds,delay2_seconds,status
15,AGCC,00,HHE,2026-08-03 05:05:29.970000,7.504756e+04,7.507773e+04,Offline
16,AGCC,00,HHN,2026-08-03 05:05:30.470000,7.504706e+04,7.507723e+04,Offline
17,AGCC,00,HHZ,2026-08-03 05:05:29.750000,7.504778e+04,7.507795e+04,Offline
27,ARAMC,00,HHE,2026-08-04 01:56:45.240000,1.125440e+00,2.460679e+00,Online
28,ARAMC,00,HHN,2026-08-04 01:56:45.390000,9.754400e-01,2.310679e+00,Online
29,ARAMC,00,HHZ,2026-08-04 01:56:43.500000,2.865440e+00,4.200679e+00,Online
75,BRJC,00,HHE,2026-08-03 21:08:17.640000,1.727989e+04,1.731006e+04,Offline
76,BRJC,00,HHN,2026-08-03 21:08:17.950000,1.727958e+04,1.730975e+04,Offline
77,BRJC,00,HHZ,2026-08-03 21:08:16.360000,1.728117e+04,1.731134e+04,Offline
78,BRJC,10,HNE,2026-08-03 21:08:17.730000,1.727980e+04,1.730997e+04,Offline
79,BRJC,10,HNN,2026-08-03 21:08:16.740000,1.728079e+04,1.731096e+04,Offline
80,BRJC,10,HNZ,2026-08-03 21:08:18.650000,1.727888e+04,1.730905e+04,Offline
138,CHI,00,HHE,2026-08-04 01:56:28.198300,8.507140e+00,1.950238e+01,Online
139,CHI,00,HHN,2026-08-04 01:56:26.958300,9.417140e+00,2.074238e+01,Online
140,CHI,00,HHZ,2026-08-04 01:56:25.918300,6.957140e+00,2.178238e+01,Online
141,CHI,10,HNE,2026-08-04 01:56:45.200000,1.610440e+00,2.500679e+00,Online
142,CHI,10,HNN,2026-08-04 01:56:45.270000,2.530440e+00,2.430679e+00,Online
143,CHI,10,HNZ,2026-08-04 01:56:46.190000,1.275440e+00,1.510679e+00,Online
243,DBB,00,HHE,2026-08-04 01:56:34.818300,1.355714e+01,1.288238e+01,Online
244,DBB,00,HHN,2026-08-04 01:56:38.058300,1.077714e+01,9.642379e+00,Online
245,DBB,00,HHZ,2026-08-04 01:56:35.758300,1.513714e+01,1.194238e+01,Online
246,DBB,10,HNE,2026-08-04 01:56:41.885000,4.480440e+00,5.815679e+00,Online
247,DBB,10,HNN,2026-08-04 01:56:39.550000,6.605440e+00,8.150679e+00,Online
248,DBB,10,HNZ,2026-08-04 01:56:39.945000,5.635440e+00,7.755679e+00,Online
249,DBB,20,EHE,2026-08-04 01:56:38.378300,1.368714e+01,9.322379e+00,Online
250,DBB,20,EHN,2026-08-04 01:56:37.658300,1.477714e+01,1.004238e+01,Online
251,DBB,20,EHZ,2026-08-04 01:56:34.868300,1.422714e+01,1.283238e+01,Online
318,GUY2C,00,HHE,2026-08-04 01:56:41.930000,3.585440e+00,5.770679e+00,Online
319,GUY2C,00,HHN,2026-08-04 01:56:43.110000,9.015440e+00,4.590679e+00,Online
320,GUY2C,00,HHZ,2026-08-04 01:56:39.340000,5.955440e+00,8.360679e+00,Online
321,GUY2C,10,HNE,2026-08-04 01:56:44.980000,3.055440e+00,2.720679e+00,Online
322,GUY2C,10,HNN,2026-08-04 01:56:45.585000,4.005440e+00,2.115679e+00,Online
323,GUY2C,10,HNZ,2026-08-04 01:56:44.570000,1.445440e+00,3.130679e+00,Online
360,MEDEC,10,HNE,2026-05-29 04:49:43.195000,5.778394e+06,5.778425e+06,Offline
361,MEDEC,10,HNN,2026-05-29 04:49:42.430000,5.778395e+06,5.778425e+06,Offline
362,MEDEC,10,HNZ,2026-05-29 04:49:42.840000,5.778395e+06,5.778425e+06,Offline
363,MOCC,10,HNE,2026-04-19 15:22:27.465000,9.196430e+06,9.196460e+06,Offline
364,MOCC,10,HNN,2026-04-19 15:22:27.935000,9.196430e+06,9.196460e+06,Offline
365,MOCC,10,HNZ,2026-04-19 15:22:27.560000,9.196430e+06,9.196460e+06,Offline
447,POP2,00,HHE,2026-08-04 00:14:02.968300,6.134557e+03,6.164732e+03,Offline
448,POP2,00,HHN,2026-08-04 00:14:02.968300,6.134557e+03,6.164732e+03,Offline
449,POP2,00,HHZ,2026-08-04 00:14:02.968300,6.134557e+03,6.164732e+03,Offline
450,POP2,40,HLE,2026-08-04 00:14:03.984500,6.133541e+03,6.163716e+03,Offline
451,POP2,40,HLN,2026-08-04 00:14:03.984500,6.133541e+03,6.163716e+03,Offline
452,POP2,40,HLZ,2026-08-04 00:14:03.984500,6.133541e+03,6.163716e+03,Offline
686,PPLP,<NA>,HHE,2026-08-04 01:56:43.498300,8.857140e+00,4.202379e+00,Online
687,PPLP,<NA>,HHN,2026-08-04 01:56:43.138300,9.127140e+00,4.562379e+00,Online
688,PPLP,<NA>,HHZ,2026-08-04 01:56:43.558300,8.357140e+00,4.142379e+00,Online
799,POP2,10,HNZ,None,NaN,NaN,N/A
816,GMALF,,HNZ,None,NaN,NaN,N/A

#### Time difference = 45 s

In [ ]:
# Request slinktool data 
port = SlinktoolExecutor.get_port('91')
comm = SlinktoolExecutor.build_command('91', port)
output = SlinktoolExecutor.request_info(comm)
solution = SlinktoolFormatter.extract_info(output)
slink_data = SlinktoolFormatter.build_dataframe(solution)
slink_data = SlinktoolFormatter.select_interest_channels(slink_data)
slink_data = SlinktoolFormatter.assign_transmission(slink_data, all_data)
slink_data = SlinktoolFormatter.order_cols(slink_data)

import warnings
with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=FutureWarning)
    final_data = DelayCalculator.add_stations_untracked(all_data, slink_data)

# Compute Delay Time
actual_time = datetime.now(UTC).replace(tzinfo=None)
final_data = DelayCalculator.compute_delays(final_data, actual_time, 'last_connection')
final_data = DelayCalculator.format_delays(final_data, delay_column='delay')
print(f'to = {actual_time}')

# Second request
period_time = 45
with tqdm(total=period_time, desc=f"Waiting {period_time} seconds to execute a new validation") as pbar:
        for _ in range(period_time):
                time.sleep(1)
                pbar.update(1)

output = SlinktoolExecutor.request_info(comm)
solution = SlinktoolFormatter.extract_info(output)
slink_data = SlinktoolFormatter.build_dataframe(solution)
slink_data = SlinktoolFormatter.select_interest_channels(slink_data)
slink_data = SlinktoolFormatter.assign_transmission(slink_data, all_data)
slink_data = SlinktoolFormatter.order_cols(slink_data)

with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=FutureWarning)
    final_data2 = DelayCalculator.add_stations_untracked(all_data, slink_data)
actual_time = datetime.now(UTC).replace(tzinfo=None)
final_data2 = DelayCalculator.compute_delays(final_data2, actual_time, 'last_connection')
final_data2 = DelayCalculator.format_delays(final_data2, delay_column='delay')

# Extract delay columns
delay1 = final_data['delay'].dt.total_seconds().fillna(np.nan).to_numpy()
delay2 = final_data2['delay'].dt.total_seconds().fillna(np.nan).to_numpy()
status = StationAnalysis.get_station_status(delay1, delay2, period_time)
final_data2['delay1_seconds'] = delay1
final_data2['delay2_seconds'] = delay2
final_data2['status'] = status
print(f'to = {actual_time}')

# Subset stations of interest 
interm_sts = ['BRJC', 'POP2', 'AGCC', 'PPLP']
perma_sts = ['ARAMC', 'CHI', 'DBB', 'GUY2C']
off_sts = ['MEDEC', 'MOCC', 'GMALF', 'UPD2']
cols = ['stid', 'loc', 'channel', 'last_connection', 'delay1_seconds', 'delay2_seconds', 'status']
res = final_data2.loc[final_data2['stid'].isin([*perma_sts, *interm_sts, *off_sts])]
res = res[cols]
res.head(50)

20:58:31 [INFO] Port stablished succesfully.
20:58:32 [INFO] Sucessful information request from slinktool.
20:58:32 [INFO] Number of sensors to be processed: 1517
20:58:32 [INFO] Success!!
20:58:32 [INFO] Dataframe created succesfully!!
20:58:32 [INFO] Selection of the 792 field sensors completed succesfully!!
20:58:32 [INFO] Transmission type assigned succesfully!!
20:58:32 [INFO] Dataframe formatted succesfully according to SGC data!!
20:58:32 [INFO] Adding stations not tracked by slinktool succesfully!!
20:58:32 [INFO] Delays succesfully computed!!
20:58:32 [INFO] Delays succesfully formatted!!

to = 2026-08-04 01:58:32.094884

Waiting 45 seconds to execute a new validation: 100%|██████████| 45/45 [00:45<00:00,  1.00s/it]
20:59:17 [INFO] Sucessful information request from slinktool.
20:59:17 [INFO] Number of sensors to be processed: 1517
20:59:17 [INFO] Success!!
20:59:17 [INFO] Dataframe created succesfully!!
20:59:17 [INFO] Selection of the 792 field sensors completed succesfully!!
20:59:17 [INFO] Transmission type assigned succesfully!!
20:59:17 [INFO] Dataframe formatted succesfully according to SGC data!!
20:59:17 [INFO] Adding stations not tracked by slinktool succesfully!!
20:59:17 [INFO] Delays succesfully computed!!
20:59:17 [INFO] Delays succesfully formatted!!

to = 2026-08-04 01:59:17.304268

,stid,loc,channel,last_connection,delay1_seconds,delay2_seconds,status
15,AGCC,00,HHE,2026-08-03 05:05:29.970000,7.518212e+04,7.522733e+04,Offline
16,AGCC,00,HHN,2026-08-03 05:05:30.470000,7.518162e+04,7.522683e+04,Offline
17,AGCC,00,HHZ,2026-08-03 05:05:29.750000,7.518234e+04,7.522755e+04,Offline
27,ARAMC,00,HHE,2026-08-04 01:59:13.560000,3.854884e+00,3.744268e+00,Online
28,ARAMC,00,HHN,2026-08-04 01:59:13.710000,3.704884e+00,3.594268e+00,Online
29,ARAMC,00,HHZ,2026-08-04 01:59:15.940000,1.474884e+00,1.364268e+00,Online
75,BRJC,00,HHE,2026-08-03 21:08:17.640000,1.741445e+04,1.745966e+04,Offline
76,BRJC,00,HHN,2026-08-03 21:08:17.950000,1.741414e+04,1.745935e+04,Offline
77,BRJC,00,HHZ,2026-08-03 21:08:16.360000,1.741573e+04,1.746094e+04,Offline
78,BRJC,10,HNE,2026-08-03 21:08:17.730000,1.741436e+04,1.745957e+04,Offline
79,BRJC,10,HNN,2026-08-03 21:08:16.740000,1.741535e+04,1.746056e+04,Offline
80,BRJC,10,HNZ,2026-08-03 21:08:18.650000,1.741344e+04,1.745865e+04,Offline
138,CHI,00,HHE,2026-08-04 01:59:00.438300,9.526584e+00,1.686597e+01,Online
139,CHI,00,HHN,2026-08-04 01:58:59.248300,9.836584e+00,1.805597e+01,Online
140,CHI,00,HHZ,2026-08-04 01:58:58.758300,9.336584e+00,1.854597e+01,Online
141,CHI,10,HNE,2026-08-04 01:59:15.735000,1.489884e+00,1.569268e+00,Online
142,CHI,10,HNN,2026-08-04 01:59:15.645000,1.354884e+00,1.659268e+00,Online
143,CHI,10,HNZ,2026-08-04 01:59:15.475000,2.554884e+00,1.829268e+00,Online
243,DBB,00,HHE,2026-08-04 01:58:59.428300,3.256584e+00,1.787597e+01,Online
244,DBB,00,HHN,2026-08-04 01:59:02.888300,5.566584e+00,1.441597e+01,Online
245,DBB,00,HHZ,2026-08-04 01:58:59.128300,1.786584e+00,1.817597e+01,Online
246,DBB,10,HNE,2026-08-04 01:59:13.250000,5.699884e+00,4.054268e+00,Online
247,DBB,10,HNN,2026-08-04 01:59:09.440000,5.454884e+00,7.864268e+00,Online
248,DBB,10,HNZ,2026-08-04 01:59:11.045000,6.704884e+00,6.259268e+00,Online
249,DBB,20,EHE,2026-08-04 01:58:59.948300,1.966584e+00,1.735597e+01,Online
250,DBB,20,EHN,2026-08-04 01:58:58.868300,4.216584e+00,1.843597e+01,Online
251,DBB,20,EHZ,2026-08-04 01:58:59.048300,4.826584e+00,1.825597e+01,Online
318,GUY2C,00,HHE,2026-08-04 01:59:14.050000,6.884884e+00,3.254268e+00,Online
319,GUY2C,00,HHN,2026-08-04 01:59:07.820000,5.824884e+00,9.484268e+00,Online
320,GUY2C,00,HHZ,2026-08-04 01:59:11.210000,2.504884e+00,6.094268e+00,Online
321,GUY2C,10,HNE,2026-08-04 01:59:14.130000,1.964884e+00,3.174268e+00,Online
322,GUY2C,10,HNN,2026-08-04 01:59:14.870000,3.434884e+00,2.434268e+00,Online
323,GUY2C,10,HNZ,2026-08-04 01:59:14.225000,4.074884e+00,3.079268e+00,Online
360,MEDEC,10,HNE,2026-05-29 04:49:43.195000,5.778529e+06,5.778574e+06,Offline
361,MEDEC,10,HNN,2026-05-29 04:49:42.430000,5.778530e+06,5.778575e+06,Offline
362,MEDEC,10,HNZ,2026-05-29 04:49:42.840000,5.778529e+06,5.778574e+06,Offline
363,MOCC,10,HNE,2026-04-19 15:22:27.465000,9.196565e+06,9.196610e+06,Offline
364,MOCC,10,HNN,2026-04-19 15:22:27.935000,9.196564e+06,9.196609e+06,Offline
365,MOCC,10,HNZ,2026-04-19 15:22:27.560000,9.196565e+06,9.196610e+06,Offline
447,POP2,00,HHE,2026-08-04 00:14:02.968300,6.269127e+03,6.314336e+03,Offline
448,POP2,00,HHN,2026-08-04 00:14:02.968300,6.269127e+03,6.314336e+03,Offline
449,POP2,00,HHZ,2026-08-04 00:14:02.968300,6.269127e+03,6.314336e+03,Offline
450,POP2,40,HLE,2026-08-04 00:14:03.984500,6.268110e+03,6.313320e+03,Offline
451,POP2,40,HLN,2026-08-04 00:14:03.984500,6.268110e+03,6.313320e+03,Offline
452,POP2,40,HLZ,2026-08-04 00:14:03.984500,6.268110e+03,6.313320e+03,Offline
686,PPLP,<NA>,HHE,2026-08-04 01:59:01.378300,6.176584e+00,1.592597e+01,Online
687,PPLP,<NA>,HHN,2026-08-04 01:59:00.868300,6.186584e+00,1.643597e+01,Online
688,PPLP,<NA>,HHZ,2026-08-04 01:59:01.158300,5.006584e+00,1.614597e+01,Online
799,POP2,10,HNZ,None,NaN,NaN,N/A
816,GMALF,,HNZ,None,NaN,NaN,N/A

#### Time difference = 60 s

In [ ]:
# Request slinktool data 
port = SlinktoolExecutor.get_port('91')
comm = SlinktoolExecutor.build_command('91', port)
output = SlinktoolExecutor.request_info(comm)
solution = SlinktoolFormatter.extract_info(output)
slink_data = SlinktoolFormatter.build_dataframe(solution)
slink_data = SlinktoolFormatter.select_interest_channels(slink_data)
slink_data = SlinktoolFormatter.assign_transmission(slink_data, all_data)
slink_data = SlinktoolFormatter.order_cols(slink_data)

import warnings
with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=FutureWarning)
    final_data = DelayCalculator.add_stations_untracked(all_data, slink_data)

# Compute Delay Time
actual_time = datetime.now(UTC).replace(tzinfo=None)
final_data = DelayCalculator.compute_delays(final_data, actual_time, 'last_connection')
final_data = DelayCalculator.format_delays(final_data, delay_column='delay')
print(f'to = {actual_time}')

# Second request
period_time = 60
with tqdm(total=period_time, desc=f"Waiting {period_time} seconds to execute a new validation") as pbar:
        for _ in range(period_time):
                time.sleep(1)
                pbar.update(1)

output = SlinktoolExecutor.request_info(comm)
solution = SlinktoolFormatter.extract_info(output)
slink_data = SlinktoolFormatter.build_dataframe(solution)
slink_data = SlinktoolFormatter.select_interest_channels(slink_data)
slink_data = SlinktoolFormatter.assign_transmission(slink_data, all_data)
slink_data = SlinktoolFormatter.order_cols(slink_data)

with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=FutureWarning)
    final_data2 = DelayCalculator.add_stations_untracked(all_data, slink_data)
actual_time = datetime.now(UTC).replace(tzinfo=None)
final_data2 = DelayCalculator.compute_delays(final_data2, actual_time, 'last_connection')
final_data2 = DelayCalculator.format_delays(final_data2, delay_column='delay')

# Extract delay columns
delay1 = final_data['delay'].dt.total_seconds().fillna(np.nan).to_numpy()
delay2 = final_data2['delay'].dt.total_seconds().fillna(np.nan).to_numpy()
status = StationAnalysis.get_station_status(delay1, delay2, period_time)
final_data2['delay1_seconds'] = delay1
final_data2['delay2_seconds'] = delay2
final_data2['status'] = status
print(f'to = {actual_time}')

# Subset stations of interest 
interm_sts = ['BRJC', 'POP2', 'AGCC', 'PPLP']
perma_sts = ['ARAMC', 'CHI', 'DBB', 'GUY2C']
off_sts = ['MEDEC', 'MOCC', 'GMALF', 'UPD2']
cols = ['stid', 'loc', 'channel', 'last_connection', 'delay1_seconds', 'delay2_seconds', 'status']
res = final_data2.loc[final_data2['stid'].isin([*perma_sts, *interm_sts, *off_sts])]
res = res[cols]
res.head(50)

21:01:10 [INFO] Port stablished succesfully.
21:01:10 [INFO] Sucessful information request from slinktool.
21:01:10 [INFO] Number of sensors to be processed: 1517
21:01:10 [INFO] Success!!
21:01:10 [INFO] Dataframe created succesfully!!
21:01:10 [INFO] Selection of the 792 field sensors completed succesfully!!
21:01:10 [INFO] Transmission type assigned succesfully!!
21:01:10 [INFO] Dataframe formatted succesfully according to SGC data!!
21:01:10 [INFO] Adding stations not tracked by slinktool succesfully!!
21:01:10 [INFO] Delays succesfully computed!!
21:01:10 [INFO] Delays succesfully formatted!!

to = 2026-08-04 02:01:10.471070

Waiting 60 seconds to execute a new validation: 100%|██████████| 60/60 [01:00<00:00,  1.00s/it]
21:02:10 [INFO] Sucessful information request from slinktool.
21:02:10 [INFO] Number of sensors to be processed: 1517
21:02:10 [INFO] Success!!
21:02:10 [INFO] Dataframe created succesfully!!
21:02:10 [INFO] Selection of the 792 field sensors completed succesfully!!
21:02:10 [INFO] Transmission type assigned succesfully!!
21:02:10 [INFO] Dataframe formatted succesfully according to SGC data!!
21:02:10 [INFO] Adding stations not tracked by slinktool succesfully!!
21:02:10 [INFO] Delays succesfully computed!!
21:02:10 [INFO] Delays succesfully formatted!!

to = 2026-08-04 02:02:10.713681

,stid,loc,channel,last_connection,delay1_seconds,delay2_seconds,status
15,AGCC,00,HHE,2026-08-03 05:05:29.970000,7.534050e+04,7.540074e+04,Offline
16,AGCC,00,HHN,2026-08-03 05:05:30.470000,7.534000e+04,7.540024e+04,Offline
17,AGCC,00,HHZ,2026-08-03 05:05:29.750000,7.534072e+04,7.540096e+04,Offline
27,ARAMC,00,HHE,2026-08-04 02:02:06.600000,1.551070e+00,4.113681e+00,Online
28,ARAMC,00,HHN,2026-08-04 02:02:06.750000,1.401070e+00,3.963681e+00,Online
29,ARAMC,00,HHZ,2026-08-04 02:02:08.980000,3.291070e+00,1.733681e+00,Online
75,BRJC,00,HHE,2026-08-03 21:08:17.640000,1.757283e+04,1.763307e+04,Offline
76,BRJC,00,HHN,2026-08-03 21:08:17.950000,1.757252e+04,1.763276e+04,Offline
77,BRJC,00,HHZ,2026-08-03 21:08:16.360000,1.757411e+04,1.763435e+04,Offline
78,BRJC,10,HNE,2026-08-03 21:08:17.730000,1.757274e+04,1.763298e+04,Offline
79,BRJC,10,HNN,2026-08-03 21:08:16.740000,1.757373e+04,1.763397e+04,Offline
80,BRJC,10,HNZ,2026-08-03 21:08:18.650000,1.757182e+04,1.763206e+04,Offline
138,CHI,00,HHE,2026-08-04 02:01:52.068300,1.550277e+01,1.864538e+01,Online
139,CHI,00,HHN,2026-08-04 02:01:50.418300,1.580277e+01,2.029538e+01,Online
140,CHI,00,HHZ,2026-08-04 02:01:52.128300,1.461277e+01,1.858538e+01,Online
141,CHI,10,HNE,2026-08-04 02:02:08.935000,2.091070e+00,1.778681e+00,Online
142,CHI,10,HNN,2026-08-04 02:02:09.550000,9.910700e-01,1.163681e+00,Online
143,CHI,10,HNZ,2026-08-04 02:02:08,2.236070e+00,2.713681e+00,Online
243,DBB,00,HHE,2026-08-04 02:01:54.778300,1.661277e+01,1.593538e+01,Online
244,DBB,00,HHN,2026-08-04 02:01:55.438300,1.894277e+01,1.527538e+01,Online
245,DBB,00,HHZ,2026-08-04 02:01:55.848300,1.663277e+01,1.486538e+01,Online
246,DBB,10,HNE,2026-08-04 02:02:06.210000,1.921070e+00,4.503681e+00,Online
247,DBB,10,HNN,2026-08-04 02:02:04.485000,6.736070e+00,6.228681e+00,Online
248,DBB,10,HNZ,2026-08-04 02:02:06.420000,3.701070e+00,4.293681e+00,Online
249,DBB,20,EHE,2026-08-04 02:01:55.938300,1.895277e+01,1.477538e+01,Online
250,DBB,20,EHN,2026-08-04 02:01:55.628300,1.683277e+01,1.508538e+01,Online
251,DBB,20,EHZ,2026-08-04 02:01:54.958300,1.853277e+01,1.575538e+01,Online
318,GUY2C,00,HHE,2026-08-04 02:02:07.970000,5.231070e+00,2.743681e+00,Online
319,GUY2C,00,HHN,2026-08-04 02:02:02.080000,4.171070e+00,8.633681e+00,Online
320,GUY2C,00,HHZ,2026-08-04 02:02:05.020000,8.101070e+00,5.693681e+00,Online
321,GUY2C,10,HNE,2026-08-04 02:02:06.910000,1.146070e+00,3.803681e+00,Online
322,GUY2C,10,HNN,2026-08-04 02:02:09.435000,1.566070e+00,1.278681e+00,Online
323,GUY2C,10,HNZ,2026-08-04 02:02:08.670000,2.391070e+00,2.043681e+00,Online
360,MEDEC,10,HNE,2026-05-29 04:49:43.195000,5.778687e+06,5.778748e+06,Offline
361,MEDEC,10,HNN,2026-05-29 04:49:42.430000,5.778688e+06,5.778748e+06,Offline
362,MEDEC,10,HNZ,2026-05-29 04:49:42.840000,5.778688e+06,5.778748e+06,Offline
363,MOCC,10,HNE,2026-04-19 15:22:27.465000,9.196723e+06,9.196783e+06,Offline
364,MOCC,10,HNN,2026-04-19 15:22:27.935000,9.196723e+06,9.196783e+06,Offline
365,MOCC,10,HNZ,2026-04-19 15:22:27.560000,9.196723e+06,9.196783e+06,Offline
447,POP2,00,HHE,2026-08-04 00:14:02.968300,6.427503e+03,6.487745e+03,Offline
448,POP2,00,HHN,2026-08-04 00:14:02.968300,6.427503e+03,6.487745e+03,Offline
449,POP2,00,HHZ,2026-08-04 00:14:02.968300,6.427503e+03,6.487745e+03,Offline
450,POP2,40,HLE,2026-08-04 00:14:03.984500,6.426487e+03,6.486729e+03,Offline
451,POP2,40,HLN,2026-08-04 00:14:03.984500,6.426487e+03,6.486729e+03,Offline
452,POP2,40,HLZ,2026-08-04 00:14:03.984500,6.426487e+03,6.486729e+03,Offline
686,PPLP,<NA>,HHE,2026-08-04 02:02:06.938300,1.034277e+01,3.775381e+00,Online
687,PPLP,<NA>,HHN,2026-08-04 02:02:07.718300,1.213277e+01,2.995381e+00,Online
688,PPLP,<NA>,HHZ,2026-08-04 02:02:08.108300,1.025277e+01,2.605381e+00,Online
799,POP2,10,HNZ,None,NaN,NaN,N/A
816,GMALF,,HNZ,None,NaN,NaN,N/A

#### Time difference = 90 s

In [ ]:
# Request slinktool data 
port = SlinktoolExecutor.get_port('91')
comm = SlinktoolExecutor.build_command('91', port)
output = SlinktoolExecutor.request_info(comm)
solution = SlinktoolFormatter.extract_info(output)
slink_data = SlinktoolFormatter.build_dataframe(solution)
slink_data = SlinktoolFormatter.select_interest_channels(slink_data)
slink_data = SlinktoolFormatter.assign_transmission(slink_data, all_data)
slink_data = SlinktoolFormatter.order_cols(slink_data)

import warnings
with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=FutureWarning)
    final_data = DelayCalculator.add_stations_untracked(all_data, slink_data)

# Compute Delay Time
actual_time = datetime.now(UTC).replace(tzinfo=None)
final_data = DelayCalculator.compute_delays(final_data, actual_time, 'last_connection')
final_data = DelayCalculator.format_delays(final_data, delay_column='delay')
print(f'to = {actual_time}')

# Second request
period_time = 90
with tqdm(total=period_time, desc=f"Waiting {period_time} seconds to execute a new validation") as pbar:
        for _ in range(period_time):
                time.sleep(1)
                pbar.update(1)

output = SlinktoolExecutor.request_info(comm)
solution = SlinktoolFormatter.extract_info(output)
slink_data = SlinktoolFormatter.build_dataframe(solution)
slink_data = SlinktoolFormatter.select_interest_channels(slink_data)
slink_data = SlinktoolFormatter.assign_transmission(slink_data, all_data)
slink_data = SlinktoolFormatter.order_cols(slink_data)

with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=FutureWarning)
    final_data2 = DelayCalculator.add_stations_untracked(all_data, slink_data)
actual_time = datetime.now(UTC).replace(tzinfo=None)
final_data2 = DelayCalculator.compute_delays(final_data2, actual_time, 'last_connection')
final_data2 = DelayCalculator.format_delays(final_data2, delay_column='delay')

# Extract delay columns
delay1 = final_data['delay'].dt.total_seconds().fillna(np.nan).to_numpy()
delay2 = final_data2['delay'].dt.total_seconds().fillna(np.nan).to_numpy()
status = StationAnalysis.get_station_status(delay1, delay2, period_time)
final_data2['delay1_seconds'] = delay1
final_data2['delay2_seconds'] = delay2
final_data2['status'] = status
print(f'to = {actual_time}')

# Subset stations of interest 
interm_sts = ['BRJC', 'POP2', 'AGCC', 'PPLP']
perma_sts = ['ARAMC', 'CHI', 'DBB', 'GUY2C']
off_sts = ['MEDEC', 'MOCC', 'GMALF', 'UPD2']
cols = ['stid', 'loc', 'channel', 'last_connection', 'delay1_seconds', 'delay2_seconds', 'status']
res = final_data2.loc[final_data2['stid'].isin([*perma_sts, *interm_sts, *off_sts])]
res = res[cols]
res.head(50)

21:02:58 [INFO] Port stablished succesfully.
21:02:58 [INFO] Sucessful information request from slinktool.
21:02:58 [INFO] Number of sensors to be processed: 1517
21:02:58 [INFO] Success!!
21:02:58 [INFO] Dataframe created succesfully!!
21:02:58 [INFO] Selection of the 792 field sensors completed succesfully!!
21:02:58 [INFO] Transmission type assigned succesfully!!
21:02:58 [INFO] Dataframe formatted succesfully according to SGC data!!
21:02:58 [INFO] Adding stations not tracked by slinktool succesfully!!
21:02:58 [INFO] Delays succesfully computed!!
21:02:58 [INFO] Delays succesfully formatted!!

to = 2026-08-04 02:02:58.978779

Waiting 90 seconds to execute a new validation: 100%|██████████| 90/90 [01:30<00:00,  1.00s/it]
21:04:29 [INFO] Sucessful information request from slinktool.
21:04:29 [INFO] Number of sensors to be processed: 1518
21:04:29 [INFO] Success!!
21:04:29 [INFO] Dataframe created succesfully!!
21:04:29 [INFO] Selection of the 792 field sensors completed succesfully!!
21:04:29 [INFO] Transmission type assigned succesfully!!
21:04:29 [INFO] Dataframe formatted succesfully according to SGC data!!
21:04:29 [INFO] Adding stations not tracked by slinktool succesfully!!
21:04:29 [INFO] Delays succesfully computed!!
21:04:29 [INFO] Delays succesfully formatted!!

to = 2026-08-04 02:04:29.283584

,stid,loc,channel,last_connection,delay1_seconds,delay2_seconds,status
15,AGCC,00,HHE,2026-08-03 05:05:29.970000,7.544901e+04,7.553931e+04,Offline
16,AGCC,00,HHN,2026-08-03 05:05:30.470000,7.544851e+04,7.553881e+04,Offline
17,AGCC,00,HHZ,2026-08-03 05:05:29.750000,7.544923e+04,7.553953e+04,Offline
27,ARAMC,00,HHE,2026-08-04 02:04:26.680000,2.938779e+00,2.603584e+00,Online
28,ARAMC,00,HHN,2026-08-04 02:04:26.830000,2.788779e+00,2.453584e+00,Online
29,ARAMC,00,HHZ,2026-08-04 02:04:24.940000,4.678779e+00,4.343584e+00,Online
75,BRJC,00,HHE,2026-08-03 21:08:17.640000,1.768134e+04,1.777164e+04,Offline
76,BRJC,00,HHN,2026-08-03 21:08:17.950000,1.768103e+04,1.777133e+04,Offline
77,BRJC,00,HHZ,2026-08-03 21:08:16.360000,1.768262e+04,1.777292e+04,Offline
78,BRJC,10,HNE,2026-08-03 21:08:17.730000,1.768125e+04,1.777155e+04,Offline
79,BRJC,10,HNN,2026-08-03 21:08:16.740000,1.768224e+04,1.777254e+04,Offline
80,BRJC,10,HNZ,2026-08-03 21:08:18.650000,1.768033e+04,1.777063e+04,Offline
138,CHI,00,HHE,2026-08-04 02:04:22.628300,1.004048e+01,6.655284e+00,Online
139,CHI,00,HHN,2026-08-04 02:04:22.358300,1.325048e+01,6.925284e+00,Online
140,CHI,00,HHZ,2026-08-04 02:04:19.968300,1.012048e+01,9.315284e+00,Online
141,CHI,10,HNE,2026-08-04 02:04:25.925000,2.978779e+00,3.358584e+00,Online
142,CHI,10,HNN,2026-08-04 02:04:26.840000,2.158779e+00,2.443584e+00,Online
143,CHI,10,HNZ,2026-08-04 02:04:26.250000,2.658779e+00,3.033584e+00,Online
243,DBB,00,HHE,2026-08-04 02:04:22.228300,1.589048e+01,7.055284e+00,Online
244,DBB,00,HHN,2026-08-04 02:04:19.478300,1.328048e+01,9.805284e+00,Online
245,DBB,00,HHZ,2026-08-04 02:04:20.328300,1.542048e+01,8.955284e+00,Online
246,DBB,10,HNE,2026-08-04 02:04:23.125000,5.923779e+00,6.158584e+00,Online
247,DBB,10,HNN,2026-08-04 02:04:23.495000,4.528779e+00,5.788584e+00,Online
248,DBB,10,HNZ,2026-08-04 02:04:26.815000,3.358779e+00,2.468584e+00,Online
249,DBB,20,EHE,2026-08-04 02:04:20.498300,1.585048e+01,8.785284e+00,Online
250,DBB,20,EHN,2026-08-04 02:04:20.338300,1.471048e+01,8.945284e+00,Online
251,DBB,20,EHZ,2026-08-04 02:04:20.928300,1.460048e+01,8.355284e+00,Online
318,GUY2C,00,HHE,2026-08-04 02:04:20.820000,8.928779e+00,8.463584e+00,Online
319,GUY2C,00,HHN,2026-08-04 02:04:21.810000,7.928779e+00,7.473584e+00,Online
320,GUY2C,00,HHZ,2026-08-04 02:04:24.500000,5.118779e+00,4.783584e+00,Online
321,GUY2C,10,HNE,2026-08-04 02:04:26.010000,1.208779e+00,3.273584e+00,Online
322,GUY2C,10,HNN,2026-08-04 02:04:24.750000,3.158779e+00,4.533584e+00,Online
323,GUY2C,10,HNZ,2026-08-04 02:04:27.480000,4.033779e+00,1.803584e+00,Online
360,MEDEC,10,HNE,2026-05-29 04:49:43.195000,5.778796e+06,5.778886e+06,Offline
361,MEDEC,10,HNN,2026-05-29 04:49:42.430000,5.778797e+06,5.778887e+06,Offline
362,MEDEC,10,HNZ,2026-05-29 04:49:42.840000,5.778796e+06,5.778886e+06,Offline
363,MOCC,10,HNE,2026-04-19 15:22:27.465000,9.196832e+06,9.196922e+06,Offline
364,MOCC,10,HNN,2026-04-19 15:22:27.935000,9.196831e+06,9.196921e+06,Offline
365,MOCC,10,HNZ,2026-04-19 15:22:27.560000,9.196831e+06,9.196922e+06,Offline
447,POP2,00,HHE,2026-08-04 00:14:02.968300,6.536010e+03,6.626315e+03,Offline
448,POP2,00,HHN,2026-08-04 00:14:02.968300,6.536010e+03,6.626315e+03,Offline
449,POP2,00,HHZ,2026-08-04 00:14:02.968300,6.536010e+03,6.626315e+03,Offline
450,POP2,40,HLE,2026-08-04 00:14:03.984500,6.534994e+03,6.625299e+03,Offline
451,POP2,40,HLN,2026-08-04 00:14:03.984500,6.534994e+03,6.625299e+03,Offline
452,POP2,40,HLZ,2026-08-04 00:14:03.984500,6.534994e+03,6.625299e+03,Offline
686,PPLP,<NA>,HHE,2026-08-04 02:04:24.088300,1.638048e+01,5.195284e+00,Online
687,PPLP,<NA>,HHN,2026-08-04 02:04:21.678300,2.002048e+01,7.605284e+00,Online
688,PPLP,<NA>,HHZ,2026-08-04 02:04:20.218300,1.628048e+01,9.065284e+00,Online
799,POP2,10,HNZ,None,NaN,NaN,N/A
816,GMALF,,HNZ,None,NaN,NaN,N/A